security:
    encoders:
        CallMe\WebBundle\Entity\User:
            algorithm: bcrypt
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        database:
            id: user_manager
        in_memory:
            memory:
                users:
                    user: { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        secured_area:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: login
                check_path: login_check
                default_target_path: /dashboard
                always_use_default_target_path: true
            logout:
                path: logout
                target: /

    access_control:
        - { path: ^/login, access: "isAnonymous()" }
        - { path: ^/register, access: "isAnonymous()" }
        - { path: ^/forgot-password, access: "isAnonymous()" }
        - { path: ^/reset-password, access: "isAnonymous()" }
