parameters:

services:
    db:
        class: PDO
        arguments: ["mysql:dbname=%database_name%", %database_user%, %database_password%]

    user_factory:
        class: CallMe\WebBundle\Entity\User\UserFactory

    user_manager:
        class: CallMe\WebBundle\Entity\User\UserManager
        arguments: [@db, @user_factory]

    s3:
        class: Aws\S3\S3Client
        factory_class: Aws\S3\S3Client
        factory_method: factory
        arguments: ["%s3_config%"]

    twilio:
        class: Services_Twilio
        arguments: [%twilio_sid%, %twilio_token%]

    audio_factory:
        class: CallMe\WebBundle\Entity\Audio\AudioFactory

    audio_manager:
        class: CallMe\WebBundle\Entity\Audio\AudioManager
        arguments: [@db, @audio_factory]

    audio_uploader:
        class: CallMe\WebBundle\Service\UploadAudio
        arguments: [@audio_manager, @s3]

    phone_factory:
        class: CallMe\WebBundle\Entity\Phone\PhoneCallFactory

    phone_call_manager:
        class: CallMe\WebBundle\Entity\Phone\PhoneCallManager
        arguments: [@db, @phone_factory]
